services:
- docker
language: bash

script:
# prepare qemu
- uname -m
#- docker run --rm --privileged multiarch/qemu-user-static:register --reset -p yes
- docker run --privileged linuxkit/binfmt:v0.6
# build image
- uname -m
- make
- docker images
- make SUFFIX=
- docker images
- make tag SUFFIX=
# Pusg images
- docker login -u $DOCKER_USERNAME bagalvitthal -p $DOCKER_PASSWORD
- make push
- make manifest SUFFIX=
