services:
- docker
language: bash
sudo: required
dist: xenial

script:
# prepare qemu
- uname -m
- sudo apt-get update
- sudo apt install -y qemu qemu-user-static qemu-user binfmt-support crossbuild-essential* pkg-config-s390x-linux-gnu
- docker run --rm --privileged multiarch/qemu-user-static:register
#- docker run --name ubuntu-ssh -p 2222:22 -itd durgadas/ubuntu-ssh 
#- docker run --rm -t s390x/ubuntu uname -m
#- docker run --privileged linuxkit/binfmt:v0.6
# build image
- uname -m
- make
- docker images
- make SUFFIX=
- docker images
- make tag SUFFIX=
# Pusg images
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- make push
- make manifest SUFFIX=
