services:
- docker
language: bash

script:
# prepare qemu
- uname -m
#- docker run --rm --privileged multiarch/qemu-user-static:register --reset -p yes
- docker run --name ubuntu-ssh -p 2222:22 -itd durgadas/ubuntu-ssh 
#- docker run --rm -t s390x/ubuntu uname -m
#- docker run --privileged linuxkit/binfmt:v0.6
# build image
- uname -m
- make
- docker images
- make SUFFIX=
- docker images
- make tag SUFFIX=
# Pusg images
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- make push
- make manifest SUFFIX=
