---
version: 2.1

jobs:
  build:
    docker:
    - image: docker:18.06.0-ce

    steps:
    - checkout
    - setup_remote_docker:
        version: 18.06.0-ce
    - run: apk add make bash git
    - run: docker info
    - run: uname -a
      # Register binfmt_misc targets for cross-building
    - run: docker run --privileged linuxkit/binfmt:v0.6
    - run: make
    - run: docker images

  build_master:
    docker:
    - image: docker:18.06.0-ce

    steps:
    - checkout
    - setup_remote_docker:
        version: 18.06.0-ce
    - run: apk add make bash git
    - run: docker info
    - run: docker run --privileged linuxkit/binfmt:v0.6
    - run: make SUFFIX=
    - run: docker images
    - run: make tag SUFFIX=
    - run: docker login -u bagalvitthal -p P@ssw0rd956101
    - run: make push
    - run: make manifest SUFFIX=

workflows:
  version: 2
  prometheus:
    jobs:
    - build:
        context: org-global
        filters:
          branches:
            ignore: master
    - build_master:
        context: org-context
        filters:
          branches:
            only: master
